development:
  adapter: postgresql
  encoding: unicode
  database: emc_development
  pool: 5
  username: emc
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: emc_test
  pool: 5
  username: emc
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: d7gjiab7s5gqp2
  pool: 5
  username: tpcobdtzkseeob
  password: 39oOuUFYY-rAEwa5rQS_uzKzLR